default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock


development:
  <<: *default
  database: wellist_development
  username: wellist
  password: wellist
  host: localhost

production:
  <<: *default
  database: wellist_production
  username: wellist
  password: wellist
  host: localhost
  
test:
  <<: *default
  database: wellist_test
  username: wellist
  password: wellist
  host: localhost
